### ISSUE TITLE
Crashes with big files

### ISSUE THREAD

**Issue by TPoupard** [edouardklein/pmjq#1]
PMJQ crashes when big files are given to it, giving a "Broken pipe" error.

Script file creating the bug-prone environment : 
[launch.sh.zip](https://github.com/edouardklein/pmjq/files/902122/launch.sh.zip)

**Comment by edouardklein** [comment]
Pourquoi diable avoir zippé le script ?

`
#!/bin/sh

root="test"
folders="input output error logs"
if [ -d $root ]; then rm -r $root; fi
mkdir $root
cd $root
mkdir $folders


for i in 100 1000 10000; do # Size in kB
    yes | head -n $((i * 500)) > input/${i}kB.txt
done

pmjq  --quit-when-empty --input=./input/ "echo" --output=./output/ --stderr=./logs/errlog --error=./error/ &> ./logs/log
`

**Comment by edouardklein** [comment]
Merci pour le rapport.

**Comment by edouardklein** [comment]
- There should be a / at the end of the argument to --stderr, otherwise pmjq will happilly overwrite all stderr dump files, always writing in the same file (here: ./logs/errlog). Instead, --stderr=./logs/errlog/ is a short form for --stderr='./logs/errlog/{{.Input 0}}', which does what one expects.

- The error occurs for any file size, because echo does not read from its standard input. Therefore when we try to write to it we get a broken pipe error.

This maybe should not bring pmjq down. Perhaps we can make it treat the file as erroneous instead. This is tricky though, because the file is not erroneous, the command is.

**Comment by edouardklein** [comment]
We'll reopen this issue if we see a use case where the command closing (or not even opening) its stdin is a correct behaviour. Until then, we consider this a problem with the command, which makes it OK to crash pmjq.
